import { normalize } from "./search.js";

/**
 * Mapa de alias: nombre del checklist → nombre exacto en el CSV de Transfermarkt.
 * Se usa cuando el checklist usa un apodo, transliteración distinta o variante.
 * @type {Record<string, string>}
 */
export const PLAYER_ALIASES = {
  // Cabo Verde — apodos
  "Diney": "Diney Borges",
  "Yannick Semedo": "Semedo",
  // Sudáfrica — typo en checklist
  "Bathasi Aubaas": "Bathusi Aubaas",
  // Canadá — nombre abreviado en CSV
  "Samuel Adekugbe": "Sam Adekugbe",
  // Marruecos — transliteración
  "Roman Saiss": "Romain Saïss",
  "Jawad El Yamio": "Jawad El Yamiq",
  // Paraguay — nombre completo vs corto
  "Matias Galarza Fonda": "Matías Galarza",
  // Australia — variante de apellido
  "Kusini Vengi": "Kusini Yengi",
  // Irán — transliteración
  "Saeed Ezatolahi": "Saeid Ezatolahi",
  // Nueva Zelanda — sin segundo apellido en CSV
  "Max Crocombe Payne": "Max Crocombe",
  // España — diminutivo
  "Dani Carvajal": "Daniel Carvajal",
  // Noruega — sin segundo nombre en CSV
  "Kristoffer Vassbakk Ajer": "Kristoffer Ajer",
  // Argelia — transliteración
  "Houssem Aquar": "Houssem Aouar",
  "Nabil Bentalab": "Nabil Bentaleb",
  "Mohammed Amoura": "Mohamed Amoura",
  // Uzbekistán — romanización alternativa
  "Rustamjon Ashurmatov": "Rustam Ashurmatov",
  "Odiljon Hamrobekov": "Odildzhon Khamrobekov",
  "Khojimat Erkinov": "Khozhimat Erkinov",
  // RD Congo — nombre completo vs parcial
  "Lionel Mpasi": "Lionel Mpasi-Nzau",
  "Meschak Elia": "Meschack Elia",
  // Ghana — nombre completo vs corto
  "Abdul Issahaku Fatawu": "Abdul Fatawu",
};

/** @type {Record<string, string>} Código de equipo → country_of_citizenship del CSV */
export const TEAM_COUNTRY = {
  MEX: "Mexico", RSA: "South Africa", KOR: "Korea, South", CZE: "Czech Republic",
  CAN: "Canada", BIH: "Bosnia-Herzegovina", QAT: "Qatar", SUI: "Switzerland",
  BRA: "Brazil", MAR: "Morocco", HAI: "Haiti", SCO: "Scotland",
  USA: "United States", PAR: "Paraguay", AUS: "Australia", TUR: "Turkey",
  GER: "Germany", CUW: "Curacao", CIV: "Cote d'Ivoire", ECU: "Ecuador",
  NED: "Netherlands", JPN: "Japan", SWE: "Sweden", TUN: "Tunisia",
  BEL: "Belgium", EGY: "Egypt", IRN: "Iran", NZL: "New Zealand",
  ESP: "Spain", CPV: "Cape Verde", KSA: "Saudi Arabia", URU: "Uruguay",
  FRA: "France", SEN: "Senegal", IRQ: "Iraq", NOR: "Norway",
  ARG: "Argentina", ALG: "Algeria", AUT: "Austria", JOR: "Jordan",
  POR: "Portugal", UZB: "Uzbekistan", COL: "Colombia", COD: "DR Congo",
  ENG: "England", CRO: "Croatia", GHA: "Ghana", PAN: "Panama",
};

/** @type {Record<string, string>} Nombres en español para los dropdowns */
export const TEAM_DISPLAY = {
  MEX: "México", RSA: "Sudáfrica", KOR: "Corea del Sur", CZE: "Rep. Checa",
  CAN: "Canadá", BIH: "Bosnia y Herz.", QAT: "Qatar", SUI: "Suiza",
  BRA: "Brasil", MAR: "Marruecos", HAI: "Haití", SCO: "Escocia",
  USA: "Estados Unidos", PAR: "Paraguay", AUS: "Australia", TUR: "Turquía",
  GER: "Alemania", CUW: "Curazao", CIV: "Costa de Marfil", ECU: "Ecuador",
  NED: "Países Bajos", JPN: "Japón", SWE: "Suecia", TUN: "Túnez",
  BEL: "Bélgica", EGY: "Egipto", IRN: "Irán", NZL: "Nueva Zelanda",
  ESP: "España", CPV: "Cabo Verde", KSA: "Arabia Saudita", URU: "Uruguay",
  FRA: "Francia", SEN: "Senegal", IRQ: "Irak", NOR: "Noruega",
  ARG: "Argentina", ALG: "Argelia", AUT: "Austria", JOR: "Jordania",
  POR: "Portugal", UZB: "Uzbekistán", COL: "Colombia", COD: "R.D. Congo",
  ENG: "Inglaterra", CRO: "Croacia", GHA: "Ghana", PAN: "Panamá",
};

/** @type {Record<string, string[]>} Grupos del Mundial 2026 */
export const GROUPS = {
  A: ["MEX", "RSA", "KOR", "CZE"],
  B: ["CAN", "BIH", "QAT", "SUI"],
  C: ["BRA", "MAR", "HAI", "SCO"],
  D: ["USA", "PAR", "AUS", "TUR"],
  E: ["GER", "CUW", "CIV", "ECU"],
  F: ["NED", "JPN", "SWE", "TUN"],
  G: ["BEL", "EGY", "IRN", "NZL"],
  H: ["ESP", "CPV", "KSA", "URU"],
  I: ["FRA", "SEN", "IRQ", "NOR"],
  J: ["ARG", "ALG", "AUT", "JOR"],
  K: ["POR", "UZB", "COL", "COD"],
  L: ["ENG", "CRO", "GHA", "PAN"],
};

/**
 * Jugadores del checklist por selección (excluye Logo y Foto de equipo).
 * @type {Record<string, Array<{code: string, name: string}>>}
 */
export const CHECKLIST = {
  MEX: [
    { code: "MEX2",  name: "Luis Malagón" },
    { code: "MEX3",  name: "Johan Vasquez" },
    { code: "MEX4",  name: "Jorge Sánchez" },
    { code: "MEX5",  name: "Cesar Montes" },
    { code: "MEX6",  name: "Jesus Gallardo" },
    { code: "MEX7",  name: "Israel Reyes" },
    { code: "MEX8",  name: "Diego Lainez" },
    { code: "MEX9",  name: "Carlos Rodriguez" },
    { code: "MEX10", name: "Edson Alvarez" },
    { code: "MEX11", name: "Orbelin Pineda" },
    { code: "MEX12", name: "Marcel Ruiz" },
    { code: "MEX14", name: "Érick Sánchez" },
    { code: "MEX15", name: "Hirving Lozano" },
    { code: "MEX16", name: "Santiago Giménez" },
    { code: "MEX17", name: "Raúl Jiménez" },
    { code: "MEX18", name: "Alexis Vega" },
    { code: "MEX19", name: "Roberto Alvarado" },
    { code: "MEX20", name: "Cesar Huerta" },
  ],
  RSA: [
    { code: "RSA2",  name: "Ronwen Williams" },
    { code: "RSA3",  name: "Sipho Chaine" },
    { code: "RSA4",  name: "Aubrey Modiba" },
    { code: "RSA5",  name: "Samukele Kabini" },
    { code: "RSA6",  name: "Mbekezeli Mbokazi" },
    { code: "RSA7",  name: "Khulumani Ndamane" },
    { code: "RSA8",  name: "Siyabonga Ngezana" },
    { code: "RSA9",  name: "Khuliso Mudau" },
    { code: "RSA10", name: "Nkosinathi Sibisi" },
    { code: "RSA11", name: "Teboho Mokoena" },
    { code: "RSA12", name: "Thalente Mbatha" },
    { code: "RSA14", name: "Bathasi Aubaas" },
    { code: "RSA15", name: "Yaya Sithole" },
    { code: "RSA16", name: "Sipho Mbule" },
    { code: "RSA17", name: "Lyle Foster" },
    { code: "RSA18", name: "Iqraam Rayners" },
    { code: "RSA19", name: "Mohau Nkota" },
    { code: "RSA20", name: "Oswin Appollis" },
  ],
  KOR: [
    { code: "KOR2",  name: "Hyeon-woo Jo" },
    { code: "KOR3",  name: "Seung-Gyu Kim" },
    { code: "KOR4",  name: "Min-jae Kim" },
    { code: "KOR5",  name: "Yu-min Cho" },
    { code: "KOR6",  name: "Young-woo Seol" },
    { code: "KOR7",  name: "Han-beom Lee" },
    { code: "KOR8",  name: "Tae-seok Lee" },
    { code: "KOR9",  name: "Myung-jae Lee" },
    { code: "KOR10", name: "Jae-sung Lee" },
    { code: "KOR11", name: "In-beom Hwang" },
    { code: "KOR12", name: "Kang-in Lee" },
    { code: "KOR14", name: "Seung-ho Paik" },
    { code: "KOR15", name: "Jens Castrop" },
    { code: "KOR16", name: "Dongg-yeong Lee" },
    { code: "KOR17", name: "Gue-sung Cho" },
    { code: "KOR18", name: "Heung-min Son" },
    { code: "KOR19", name: "Hee-chan Hwang" },
    { code: "KOR20", name: "Hyeon-Gyu Oh" },
  ],
  CZE: [
    { code: "CZE2",  name: "Matej Kovar" },
    { code: "CZE3",  name: "Jindrich Stanek" },
    { code: "CZE4",  name: "Ladislav Krejci" },
    { code: "CZE5",  name: "Vladimir Coufal" },
    { code: "CZE6",  name: "Jaroslav Zeleny" },
    { code: "CZE7",  name: "Tomas Holes" },
    { code: "CZE8",  name: "David Zima" },
    { code: "CZE9",  name: "Michal Sadilek" },
    { code: "CZE10", name: "Lukas Provod" },
    { code: "CZE11", name: "Lukas Cerv" },
    { code: "CZE12", name: "Tomas Soucek" },
    { code: "CZE14", name: "Pavel Sulc" },
    { code: "CZE15", name: "Matej Vydra" },
    { code: "CZE16", name: "Vasil Kusej" },
    { code: "CZE17", name: "Tomas Chory" },
    { code: "CZE18", name: "Vaclav Cerny" },
    { code: "CZE19", name: "Adam Hlozek" },
    { code: "CZE20", name: "Patrik Schick" },
  ],
  CAN: [
    { code: "CAN2",  name: "Dayne St. Clair" },
    { code: "CAN3",  name: "Alphonso Davies" },
    { code: "CAN4",  name: "Alistair Johnston" },
    { code: "CAN5",  name: "Samuel Adekugbe" },
    { code: "CAN6",  name: "Riche Larvea" },
    { code: "CAN7",  name: "Derek Cornelius" },
    { code: "CAN8",  name: "Moïse Bombito" },
    { code: "CAN9",  name: "Kamal Miller" },
    { code: "CAN10", name: "Stephen Eustáquio" },
    { code: "CAN11", name: "Ismaël Koné" },
    { code: "CAN12", name: "Jonathan Osorio" },
    { code: "CAN14", name: "Jacob Shaffelburg" },
    { code: "CAN15", name: "Mathieu Choinière" },
    { code: "CAN16", name: "Niko Sigur" },
    { code: "CAN17", name: "Tajon Buchanan" },
    { code: "CAN18", name: "Liam Millar" },
    { code: "CAN19", name: "Cyle Larin" },
    { code: "CAN20", name: "Jonathan David" },
  ],
  BIH: [
    { code: "BIH2",  name: "Nikola Vasilj" },
    { code: "BIH3",  name: "Amer Dedic" },
    { code: "BIH4",  name: "Sead Kolasinac" },
    { code: "BIH5",  name: "Tarik Muharemovic" },
    { code: "BIH6",  name: "Nihad Mujakic" },
    { code: "BIH7",  name: "Nikola Katic" },
    { code: "BIH8",  name: "Amir Hadziahmetovic" },
    { code: "BIH9",  name: "Benjamin Tahirovic" },
    { code: "BIH10", name: "Armin Gigovic" },
    { code: "BIH11", name: "Ivan Sunjic" },
    { code: "BIH12", name: "Ivan Basic" },
    { code: "BIH14", name: "Dzenis Burnic" },
    { code: "BIH15", name: "Esmir Bajraktarevic" },
    { code: "BIH16", name: "Amar Memic" },
    { code: "BIH17", name: "Ermedin Demirovic" },
    { code: "BIH18", name: "Edin Dzeko" },
    { code: "BIH19", name: "Samed Bazdar" },
    { code: "BIH20", name: "Haris Tabakovic" },
  ],
  QAT: [
    { code: "QAT2",  name: "Meshaal Barsham" },
    { code: "QAT3",  name: "Sultan Albrake" },
    { code: "QAT4",  name: "Lucas Mendes" },
    { code: "QAT5",  name: "Homam Ahmed" },
    { code: "QAT6",  name: "Boualem Khoukhi" },
    { code: "QAT7",  name: "Pedro Miguel" },
    { code: "QAT8",  name: "Tarek Salman" },
    { code: "QAT9",  name: "Mohamed Al-Mannai" },
    { code: "QAT10", name: "Karim Boudiaf" },
    { code: "QAT11", name: "Assim Madibo" },
    { code: "QAT12", name: "Ahmed Fatehi" },
    { code: "QAT14", name: "Mohammed Waad" },
    { code: "QAT15", name: "Abdulaziz Hatem" },
    { code: "QAT16", name: "Hassan Al-Haydos" },
    { code: "QAT17", name: "Edmilson Junior" },
    { code: "QAT18", name: "Akram Hassan Afif" },
    { code: "QAT19", name: "Ahmed Al Ganehi" },
    { code: "QAT20", name: "Almoez Ali" },
  ],
  SUI: [
    { code: "SUI2",  name: "Gregor Kobel" },
    { code: "SUI3",  name: "Yvon Mvogo" },
    { code: "SUI4",  name: "Manuel Akanji" },
    { code: "SUI5",  name: "Ricardo Rodriguez" },
    { code: "SUI6",  name: "Nico Elvedi" },
    { code: "SUI7",  name: "Aurèle Amenda" },
    { code: "SUI8",  name: "Silvan Widmer" },
    { code: "SUI9",  name: "Granit Xhaka" },
    { code: "SUI10", name: "Denis Zakaria" },
    { code: "SUI11", name: "Remo Freuler" },
    { code: "SUI12", name: "Fabian Rieder" },
    { code: "SUI14", name: "Ardon Jashari" },
    { code: "SUI15", name: "Johan Manzambi" },
    { code: "SUI16", name: "Michel Aebischer" },
    { code: "SUI17", name: "Breel Embolo" },
    { code: "SUI18", name: "Ruben Vargas" },
    { code: "SUI19", name: "Dan Ndoye" },
    { code: "SUI20", name: "Zeki Amdouni" },
  ],
  BRA: [
    { code: "BRA2",  name: "Alisson" },
    { code: "BRA3",  name: "Bento" },
    { code: "BRA4",  name: "Marquinhos" },
    { code: "BRA5",  name: "Éder Militão" },
    { code: "BRA6",  name: "Gabriel Magalhães" },
    { code: "BRA7",  name: "Danilo" },
    { code: "BRA8",  name: "Wesley" },
    { code: "BRA9",  name: "Lucas Paquetá" },
    { code: "BRA10", name: "Casemiro" },
    { code: "BRA11", name: "Bruno Guimarães" },
    { code: "BRA12", name: "Luiz Henrique" },
    { code: "BRA14", name: "Vinicius Júnior" },
    { code: "BRA15", name: "Rodrygo" },
    { code: "BRA16", name: "João Pedro" },
    { code: "BRA17", name: "Matheus Cunha" },
    { code: "BRA18", name: "Gabriel Martinelli" },
    { code: "BRA19", name: "Raphinha" },
    { code: "BRA20", name: "Estévão" },
  ],
  MAR: [
    { code: "MAR2",  name: "Yassine Bounou" },
    { code: "MAR3",  name: "Munir El Kajoui" },
    { code: "MAR4",  name: "Achraf Hakimi" },
    { code: "MAR5",  name: "Noussair Mazraoui" },
    { code: "MAR6",  name: "Nayef Aguerd" },
    { code: "MAR7",  name: "Roman Saiss" },
    { code: "MAR8",  name: "Jawad El Yamio" },
    { code: "MAR9",  name: "Adam Masina" },
    { code: "MAR10", name: "Sofyan Amrabat" },
    { code: "MAR11", name: "Azzedine Ounahi" },
    { code: "MAR12", name: "Eliesse Ben Seghir" },
    { code: "MAR14", name: "Bilal El Khannouss" },
    { code: "MAR15", name: "Ismael Saibari" },
    { code: "MAR16", name: "Youssef En-Nesyri" },
    { code: "MAR17", name: "Abde Ezzalzouli" },
    { code: "MAR18", name: "Soufiane Rahimi" },
    { code: "MAR19", name: "Brahim Diaz" },
    { code: "MAR20", name: "Ayoub El Kaabi" },
  ],
  HAI: [
    { code: "HAI2",  name: "Johny Placide" },
    { code: "HAI3",  name: "Carlens Arcus" },
    { code: "HAI4",  name: "Martin Expérience" },
    { code: "HAI5",  name: "Jean-Kevin Duverne" },
    { code: "HAI6",  name: "Ricardo Adé" },
    { code: "HAI7",  name: "Duke Lacroix" },
    { code: "HAI8",  name: "Garven Metusala" },
    { code: "HAI9",  name: "Hannes Delcroix" },
    { code: "HAI10", name: "Leverton Pierre" },
    { code: "HAI11", name: "Danley Jean Jacques" },
    { code: "HAI12", name: "Jean-Ricner Bellegarde" },
    { code: "HAI14", name: "Christopher Attys" },
    { code: "HAI15", name: "Derrick Etienne Jr" },
    { code: "HAI16", name: "Josue Casimir" },
    { code: "HAI17", name: "Ruben Providence" },
    { code: "HAI18", name: "Duckens Nazon" },
    { code: "HAI19", name: "Louicius Deedson" },
    { code: "HAI20", name: "Frantzdy Pierrot" },
  ],
  SCO: [
    { code: "SCO2",  name: "Angus Gunn" },
    { code: "SCO3",  name: "Jack Hendry" },
    { code: "SCO4",  name: "Kieran Tierney" },
    { code: "SCO5",  name: "Aaron Hickey" },
    { code: "SCO6",  name: "Andrew Robertson" },
    { code: "SCO7",  name: "Scott McKenna" },
    { code: "SCO8",  name: "John Souttar" },
    { code: "SCO9",  name: "Anthony Ralston" },
    { code: "SCO10", name: "Grant Hanley" },
    { code: "SCO11", name: "Scott McTominay" },
    { code: "SCO12", name: "Billy Gilmour" },
    { code: "SCO14", name: "Lewis Ferguson" },
    { code: "SCO15", name: "Ryan Christie" },
    { code: "SCO16", name: "Kenny McLean" },
    { code: "SCO17", name: "John McGinn" },
    { code: "SCO18", name: "Lyndon Dykes" },
    { code: "SCO19", name: "Che Adams" },
    { code: "SCO20", name: "Ben Gannon-Doak" },
  ],
  USA: [
    { code: "USA2",  name: "Matt Freese" },
    { code: "USA3",  name: "Chris Richards" },
    { code: "USA4",  name: "Tim Ream" },
    { code: "USA5",  name: "Mark McKenzie" },
    { code: "USA6",  name: "Alex Freeman" },
    { code: "USA7",  name: "Antonee Robinson" },
    { code: "USA8",  name: "Tyler Adams" },
    { code: "USA9",  name: "Tanner Tessmann" },
    { code: "USA10", name: "Weston McKennie" },
    { code: "USA11", name: "Christian Roldan" },
    { code: "USA12", name: "Timothy Weah" },
    { code: "USA14", name: "Diego Luna" },
    { code: "USA15", name: "Malik Tillman" },
    { code: "USA16", name: "Christian Pulisic" },
    { code: "USA17", name: "Brenden Aaronson" },
    { code: "USA18", name: "Ricardo Pepi" },
    { code: "USA19", name: "Haji Wright" },
    { code: "USA20", name: "Folarin Balogun" },
  ],
  PAR: [
    { code: "PAR2",  name: "Roberto Fernandez" },
    { code: "PAR3",  name: "Orlando Gill" },
    { code: "PAR4",  name: "Gustavo Gomez" },
    { code: "PAR5",  name: "Fabián Balbuena" },
    { code: "PAR6",  name: "Juan José Cáceres" },
    { code: "PAR7",  name: "Omar Alderete" },
    { code: "PAR8",  name: "Junior Alonso" },
    { code: "PAR9",  name: "Mathías Villasanti" },
    { code: "PAR10", name: "Diego Gomez" },
    { code: "PAR11", name: "Damián Bobadilla" },
    { code: "PAR12", name: "Andres Cubas" },
    { code: "PAR14", name: "Matias Galarza Fonda" },
    { code: "PAR15", name: "Julio Enciso" },
    { code: "PAR16", name: "Alejandro Romero Gamarra" },
    { code: "PAR17", name: "Miguel Almirón" },
    { code: "PAR18", name: "Ramon Sosa" },
    { code: "PAR19", name: "Angel Romero" },
    { code: "PAR20", name: "Antonio Sanabria" },
  ],
  AUS: [
    { code: "AUS2",  name: "Mathew Ryan" },
    { code: "AUS3",  name: "Joe Gauci" },
    { code: "AUS4",  name: "Harry Souttar" },
    { code: "AUS5",  name: "Alessandro Circati" },
    { code: "AUS6",  name: "Jordan Bos" },
    { code: "AUS7",  name: "Aziz Behich" },
    { code: "AUS8",  name: "Cameron Burgess" },
    { code: "AUS9",  name: "Lewis Miller" },
    { code: "AUS10", name: "Milos Degenek" },
    { code: "AUS11", name: "Jackson Irvine" },
    { code: "AUS12", name: "Riley McGree" },
    { code: "AUS14", name: "Aiden O'Neill" },
    { code: "AUS15", name: "Connor Metcalfe" },
    { code: "AUS16", name: "Patrick Yazbek" },
    { code: "AUS17", name: "Craig Goodwin" },
    { code: "AUS18", name: "Kusini Vengi" },
    { code: "AUS19", name: "Nestory Irankunda" },
    { code: "AUS20", name: "Mohamed Touré" },
  ],
  TUR: [
    { code: "TUR2",  name: "Ugurcan Cakir" },
    { code: "TUR3",  name: "Mert Muldur" },
    { code: "TUR4",  name: "Zeki Celik" },
    { code: "TUR5",  name: "Abdulkerim Bardakci" },
    { code: "TUR6",  name: "Caglar Soyuncu" },
    { code: "TUR7",  name: "Merih Demiral" },
    { code: "TUR8",  name: "Ferdi Kadioglu" },
    { code: "TUR9",  name: "Kaan Ayhan" },
    { code: "TUR10", name: "Ismail Yuksek" },
    { code: "TUR11", name: "Hakan Calhanoglu" },
    { code: "TUR12", name: "Orkun Kokcu" },
    { code: "TUR14", name: "Arda Guler" },
    { code: "TUR15", name: "Irfan Can Kahveci" },
    { code: "TUR16", name: "Yunus Akgun" },
    { code: "TUR17", name: "Can Uzun" },
    { code: "TUR18", name: "Baris Alper Yilmaz" },
    { code: "TUR19", name: "Kerem Akturkoglu" },
    { code: "TUR20", name: "Kenan Yildiz" },
  ],
  GER: [
    { code: "GER2",  name: "Marc-André ter Stegen" },
    { code: "GER3",  name: "Jonathan Tah" },
    { code: "GER4",  name: "David Raum" },
    { code: "GER5",  name: "Nico Schlotterbeck" },
    { code: "GER6",  name: "Antonio Rüdiger" },
    { code: "GER7",  name: "Waldemar Anton" },
    { code: "GER8",  name: "Ridle Baku" },
    { code: "GER9",  name: "Maximilian Mittelstadt" },
    { code: "GER10", name: "Joshua Kimmich" },
    { code: "GER11", name: "Florian Wirtz" },
    { code: "GER12", name: "Felix Nmecha" },
    { code: "GER14", name: "Leon Goretzka" },
    { code: "GER15", name: "Jamal Musiala" },
    { code: "GER16", name: "Serge Gnabry" },
    { code: "GER17", name: "Kai Havertz" },
    { code: "GER18", name: "Leroy Sane" },
    { code: "GER19", name: "Karim Adeyemi" },
    { code: "GER20", name: "Nick Woltemade" },
  ],
  CUW: [
    { code: "CUW2",  name: "Eloy Room" },
    { code: "CUW3",  name: "Armando Obispo" },
    { code: "CUW4",  name: "Sherel Floranus" },
    { code: "CUW5",  name: "Jurien Gaari" },
    { code: "CUW6",  name: "Joshua Brenet" },
    { code: "CUW7",  name: "Roshon Van Eijma" },
    { code: "CUW8",  name: "Shurandy Sambo" },
    { code: "CUW9",  name: "Livano Comenencia" },
    { code: "CUW10", name: "Godfried Roemeratoe" },
    { code: "CUW11", name: "Juninho Bacuna" },
    { code: "CUW12", name: "Leandro Bacuna" },
    { code: "CUW14", name: "Tahith Chong" },
    { code: "CUW15", name: "Kenji Gorre" },
    { code: "CUW16", name: "Jearl Margaritha" },
    { code: "CUW17", name: "Jurgen Locadia" },
    { code: "CUW18", name: "Jeremy Antonisse" },
    { code: "CUW19", name: "Gervane Kastaneer" },
    { code: "CUW20", name: "Sontje Hansen" },
  ],
  CIV: [
    { code: "CIV2",  name: "Yahia Fofana" },
    { code: "CIV3",  name: "Ghislain Konan" },
    { code: "CIV4",  name: "Wilfried Singo" },
    { code: "CIV5",  name: "Odilon Kossounou" },
    { code: "CIV6",  name: "Evan Ndicka" },
    { code: "CIV7",  name: "Willy Boly" },
    { code: "CIV8",  name: "Emmanuel Agbadou" },
    { code: "CIV9",  name: "Ousmane Diomande" },
    { code: "CIV10", name: "Franck Kessie" },
    { code: "CIV11", name: "Seko Fofana" },
    { code: "CIV12", name: "Ibrahim Sangare" },
    { code: "CIV14", name: "Jean-Philippe Gbamin" },
    { code: "CIV15", name: "Amad Diallo" },
    { code: "CIV16", name: "Sébastien Haller" },
    { code: "CIV17", name: "Simon Adingra" },
    { code: "CIV18", name: "Yan Diomande" },
    { code: "CIV19", name: "Evann Guessand" },
    { code: "CIV20", name: "Oumar Diakite" },
  ],
  ECU: [
    { code: "ECU2",  name: "Hernán Galíndez" },
    { code: "ECU3",  name: "Gonzalo Valle" },
    { code: "ECU4",  name: "Piero Hincapié" },
    { code: "ECU5",  name: "Pervis Estupiñán" },
    { code: "ECU6",  name: "Willian Pacho" },
    { code: "ECU7",  name: "Ángelo Preciado" },
    { code: "ECU8",  name: "Joel Ordóñez" },
    { code: "ECU9",  name: "Moises Caicedo" },
    { code: "ECU10", name: "Alan Franco" },
    { code: "ECU11", name: "Kendry Paez" },
    { code: "ECU12", name: "Pedro Vite" },
    { code: "ECU14", name: "John Veboah" },
    { code: "ECU15", name: "Leonardo Campana" },
    { code: "ECU16", name: "Gonzalo Plata" },
    { code: "ECU17", name: "Nilson Angulo" },
    { code: "ECU18", name: "Alan Minda" },
    { code: "ECU19", name: "Kevin Rodriguez" },
    { code: "ECU20", name: "Enner Valencia" },
  ],
  NED: [
    { code: "NED2",  name: "Bart Verbruggen" },
    { code: "NED3",  name: "Virgil van Dijk" },
    { code: "NED4",  name: "Micky van de Ven" },
    { code: "NED5",  name: "Jurrien Timber" },
    { code: "NED6",  name: "Denzel Dumfries" },
    { code: "NED7",  name: "Nathan Aké" },
    { code: "NED8",  name: "Jeremie Frimpong" },
    { code: "NED9",  name: "Jan Paul van Hecke" },
    { code: "NED10", name: "Tijjani Reijnders" },
    { code: "NED11", name: "Ryan Gravenberch" },
    { code: "NED12", name: "Teun Koopmeiners" },
    { code: "NED14", name: "Frenkie de Jong" },
    { code: "NED15", name: "Xavi Simons" },
    { code: "NED16", name: "Justin Kluivert" },
    { code: "NED17", name: "Memphis Depay" },
    { code: "NED18", name: "Donyell Malen" },
    { code: "NED19", name: "Wout Weghorst" },
    { code: "NED20", name: "Cody Gakpo" },
  ],
  JPN: [
    { code: "JPN2",  name: "Zion Suzuki" },
    { code: "JPN3",  name: "Henry Heroki Mochizuki" },
    { code: "JPN4",  name: "Ayumu Seko" },
    { code: "JPN5",  name: "Junnosuke Suzuki" },
    { code: "JPN6",  name: "Shogo Taniguchi" },
    { code: "JPN7",  name: "Tsuyoshi Watanabe" },
    { code: "JPN8",  name: "Kaishu Sano" },
    { code: "JPN9",  name: "Yuki Soma" },
    { code: "JPN10", name: "Ao Tanaka" },
    { code: "JPN11", name: "Daichi Kamada" },
    { code: "JPN12", name: "Takefusa Kubo" },
    { code: "JPN14", name: "Ritsu Doan" },
    { code: "JPN15", name: "Keito Nakamura" },
    { code: "JPN16", name: "Takumi Minamino" },
    { code: "JPN17", name: "Shuto Machino" },
    { code: "JPN18", name: "Junya Ito" },
    { code: "JPN19", name: "Koki Ogawa" },
    { code: "JPN20", name: "Ayase Ueda" },
  ],
  SWE: [
    { code: "SWE2",  name: "Victor Johansson" },
    { code: "SWE3",  name: "Isak Hien" },
    { code: "SWE4",  name: "Gabriel Gudmundsson" },
    { code: "SWE5",  name: "Emil Holm" },
    { code: "SWE6",  name: "Victor Nilsson Lindelöf" },
    { code: "SWE7",  name: "Gustaf Lagerbielke" },
    { code: "SWE8",  name: "Lucas Bergvall" },
    { code: "SWE9",  name: "Hugo Larsson" },
    { code: "SWE10", name: "Jesper Karlström" },
    { code: "SWE11", name: "Yasin Ayari" },
    { code: "SWE12", name: "Mattias Svanberg" },
    { code: "SWE14", name: "Daniel Svensson" },
    { code: "SWE15", name: "Ken Sema" },
    { code: "SWE16", name: "Roony Bardghji" },
    { code: "SWE17", name: "Dejan Kulusevski" },
    { code: "SWE18", name: "Anthony Elanga" },
    { code: "SWE19", name: "Alexander Isak" },
    { code: "SWE20", name: "Viktor Gyökeres" },
  ],
  TUN: [
    { code: "TUN2",  name: "Bechir Ben Said" },
    { code: "TUN3",  name: "Aymen Dahmen" },
    { code: "TUN4",  name: "Yan Valery" },
    { code: "TUN5",  name: "Montassar Talbi" },
    { code: "TUN6",  name: "Yassine Meriah" },
    { code: "TUN7",  name: "Ali Abdi" },
    { code: "TUN8",  name: "Dylan Bronn" },
    { code: "TUN9",  name: "Ellyes Skhiri" },
    { code: "TUN10", name: "Aissa Laidouni" },
    { code: "TUN11", name: "Ferjani Sassi" },
    { code: "TUN12", name: "Mohamed Ali Ben Romdhane" },
    { code: "TUN14", name: "Hannibal Mejbri" },
    { code: "TUN15", name: "Elias Achouri" },
    { code: "TUN16", name: "Elias Saad" },
    { code: "TUN17", name: "Hazem Mastouri" },
    { code: "TUN18", name: "Ismael Gharbi" },
    { code: "TUN19", name: "Sayfallah Ltaief" },
    { code: "TUN20", name: "Naim Sliti" },
  ],
  BEL: [
    { code: "BEL2",  name: "Thibaut Courtois" },
    { code: "BEL3",  name: "Arthur Theate" },
    { code: "BEL4",  name: "Timothy Castagne" },
    { code: "BEL5",  name: "Zeno Debast" },
    { code: "BEL6",  name: "Brandon Mechele" },
    { code: "BEL7",  name: "Maxim De Cuyper" },
    { code: "BEL8",  name: "Thomas Meunier" },
    { code: "BEL9",  name: "Youri Tielemans" },
    { code: "BEL10", name: "Amadou Onana" },
    { code: "BEL11", name: "Nicolas Raskin" },
    { code: "BEL12", name: "Alexis Saelemaekers" },
    { code: "BEL14", name: "Hans Vanaken" },
    { code: "BEL15", name: "Kevin De Bruyne" },
    { code: "BEL16", name: "Jérémy Doku" },
    { code: "BEL17", name: "Charles De Ketelaere" },
    { code: "BEL18", name: "Leandro Trossard" },
    { code: "BEL19", name: "Loïs Openda" },
    { code: "BEL20", name: "Romelu Lukaku" },
  ],
  EGY: [
    { code: "EGY2",  name: "Mohamed El Shenawy" },
    { code: "EGY3",  name: "Mohamed Hany" },
    { code: "EGY4",  name: "Mohamed Hamdy" },
    { code: "EGY5",  name: "Yasser Ibrahim" },
    { code: "EGY6",  name: "Khaled Sobhi" },
    { code: "EGY7",  name: "Ramy Rabia" },
    { code: "EGY8",  name: "Hossam Abdelmaguid" },
    { code: "EGY9",  name: "Ahmed Fatouh" },
    { code: "EGY10", name: "Marwan Attia" },
    { code: "EGY11", name: "Zizo" },
    { code: "EGY12", name: "Hamdy Fathy" },
    { code: "EGY14", name: "Mohamed Lasheen" },
    { code: "EGY15", name: "Emam Ashour" },
    { code: "EGY16", name: "Osama Faisal" },
    { code: "EGY17", name: "Mohamed Salah" },
    { code: "EGY18", name: "Mostafa Mohamed" },
    { code: "EGY19", name: "Trezeguet" },
    { code: "EGY20", name: "Omar Marmoush" },
  ],
  IRN: [
    { code: "IRN2",  name: "Alireza Beiranvand" },
    { code: "IRN3",  name: "Morteza Pouraliganji" },
    { code: "IRN4",  name: "Ehsan Hajsafi" },
    { code: "IRN5",  name: "Milad Mohammadi" },
    { code: "IRN6",  name: "Shojae Khalilzadeh" },
    { code: "IRN7",  name: "Ramin Rezaeian" },
    { code: "IRN8",  name: "Hossein Kanaani" },
    { code: "IRN9",  name: "Sadegh Moharrami" },
    { code: "IRN10", name: "Saleh Hardani" },
    { code: "IRN11", name: "Saeed Ezatolahi" },
    { code: "IRN12", name: "Saman Ghoddos" },
    { code: "IRN14", name: "Omid Noorafkan" },
    { code: "IRN15", name: "Roozbeh Cheshmi" },
    { code: "IRN16", name: "Mohammad Mohebi" },
    { code: "IRN17", name: "Sardar Azmoun" },
    { code: "IRN18", name: "Mehdi Taremi" },
    { code: "IRN19", name: "Alireza Jahanbakhsh" },
    { code: "IRN20", name: "Ali Gholizadeh" },
  ],
  NZL: [
    { code: "NZL2",  name: "Max Crocombe Payne" },
    { code: "NZL3",  name: "Alex Paulsen" },
    { code: "NZL4",  name: "Michael Boxall" },
    { code: "NZL5",  name: "Liberato Cacace" },
    { code: "NZL6",  name: "Tim Payne" },
    { code: "NZL7",  name: "Tyler Bindon" },
    { code: "NZL8",  name: "Francis de Vries" },
    { code: "NZL9",  name: "Finn Surman" },
    { code: "NZL10", name: "Joe Bell" },
    { code: "NZL11", name: "Sarpreet Singh" },
    { code: "NZL12", name: "Ryan Thomas" },
    { code: "NZL14", name: "Matthew Garbett" },
    { code: "NZL15", name: "Marko Stamenić" },
    { code: "NZL16", name: "Ben Old" },
    { code: "NZL17", name: "Chris Wood" },
    { code: "NZL18", name: "Elijah Just" },
    { code: "NZL19", name: "Callum McCowatt" },
    { code: "NZL20", name: "Kosta Barbarouses" },
  ],
  ESP: [
    { code: "ESP2",  name: "Unai Simon" },
    { code: "ESP3",  name: "Robin Le Normand" },
    { code: "ESP4",  name: "Aymeric Laporte" },
    { code: "ESP5",  name: "Dean Huijsen" },
    { code: "ESP6",  name: "Pedro Porro" },
    { code: "ESP7",  name: "Dani Carvajal" },
    { code: "ESP8",  name: "Marc Cucurella" },
    { code: "ESP9",  name: "Martín Zubimendi" },
    { code: "ESP10", name: "Rodri" },
    { code: "ESP11", name: "Pedri" },
    { code: "ESP12", name: "Fabian Ruiz" },
    { code: "ESP14", name: "Mikel Merino" },
    { code: "ESP15", name: "Lamine Yamal" },
    { code: "ESP16", name: "Dani Olmo" },
    { code: "ESP17", name: "Nico Williams" },
    { code: "ESP18", name: "Ferran Torres" },
    { code: "ESP19", name: "Álvaro Morata" },
    { code: "ESP20", name: "Mikel Oyarzabal" },
  ],
  CPV: [
    { code: "CPV2",  name: "Vozinha" },
    { code: "CPV3",  name: "Logan Costa" },
    { code: "CPV4",  name: "Pico" },
    { code: "CPV5",  name: "Diney" },
    { code: "CPV6",  name: "Steven Moreira" },
    { code: "CPV7",  name: "Wagner Pina" },
    { code: "CPV8",  name: "Joao Paulo" },
    { code: "CPV9",  name: "Yannick Semedo" },
    { code: "CPV10", name: "Kevin Pina" },
    { code: "CPV11", name: "Patrick Andrade" },
    { code: "CPV12", name: "Jamiro Monteiro" },
    { code: "CPV14", name: "Deroy Duarte" },
    { code: "CPV15", name: "Garry Rodrigues" },
    { code: "CPV16", name: "Jovane Cabral" },
    { code: "CPV17", name: "Ryan Mendes" },
    { code: "CPV18", name: "Dailon Livramento" },
    { code: "CPV19", name: "Willy Semedo" },
    { code: "CPV20", name: "Bebe" },
  ],
  KSA: [
    { code: "KSA2",  name: "Nawaf Alaqidi" },
    { code: "KSA3",  name: "Abdulrahman Al-Sanbi" },
    { code: "KSA4",  name: "Saud Abdulhamid" },
    { code: "KSA5",  name: "Nawaf Bouwashl" },
    { code: "KSA6",  name: "Jihad Thakri" },
    { code: "KSA7",  name: "Moteb Al-Harbi" },
    { code: "KSA8",  name: "Hassan Altambakti" },
    { code: "KSA9",  name: "Musab Aljuwayr" },
    { code: "KSA10", name: "Ziyad Aljohani" },
    { code: "KSA11", name: "Abdullah Alkhaibari" },
    { code: "KSA12", name: "Nasser Aldawsari" },
    { code: "KSA14", name: "Saleh Abu Alshamat" },
    { code: "KSA15", name: "Marwan Alsahafi" },
    { code: "KSA16", name: "Salem Aldawsari" },
    { code: "KSA17", name: "Abdulrahman Al-Aboud" },
    { code: "KSA18", name: "Feras Akbrikan" },
    { code: "KSA19", name: "Saleh Alshehri" },
    { code: "KSA20", name: "Abdullah Al-Hamdan" },
  ],
  URU: [
    { code: "URU2",  name: "Sergio Rochet" },
    { code: "URU3",  name: "Santiago Mele" },
    { code: "URU4",  name: "Ronald Araujo" },
    { code: "URU5",  name: "José María Giménez" },
    { code: "URU6",  name: "Sebastian Caceres" },
    { code: "URU7",  name: "Mathias Olivera" },
    { code: "URU8",  name: "Guillermo Varela" },
    { code: "URU9",  name: "Nahitan Nandez" },
    { code: "URU10", name: "Federico Valverde" },
    { code: "URU11", name: "Giorgian De Arrascaeta" },
    { code: "URU12", name: "Rodrigo Bentancur" },
    { code: "URU14", name: "Manuel Ugarte" },
    { code: "URU15", name: "Nicolás de la Cruz" },
    { code: "URU16", name: "Maxi Araujo" },
    { code: "URU17", name: "Darwin Núñez" },
    { code: "URU18", name: "Federico Viñas" },
    { code: "URU19", name: "Rodrigo Aguirre" },
    { code: "URU20", name: "Facundo Pellistri" },
  ],
  FRA: [
    { code: "FRA2",  name: "Mike Maignan" },
    { code: "FRA3",  name: "Theo Hernandez" },
    { code: "FRA4",  name: "William Saliba" },
    { code: "FRA5",  name: "Jules Kounde" },
    { code: "FRA6",  name: "Ibrahima Konate" },
    { code: "FRA7",  name: "Dayot Upamecano" },
    { code: "FRA8",  name: "Lucas Digne" },
    { code: "FRA9",  name: "Aurélien Tchouaméni" },
    { code: "FRA10", name: "Eduardo Camavinga" },
    { code: "FRA11", name: "Manu Kone" },
    { code: "FRA12", name: "Adrien Rabiot" },
    { code: "FRA14", name: "Michael Olise" },
    { code: "FRA15", name: "Ousmane Dembele" },
    { code: "FRA16", name: "Bradley Barcola" },
    { code: "FRA17", name: "Désiré Doué" },
    { code: "FRA18", name: "Kingsley Coman" },
    { code: "FRA19", name: "Hugo Ekitike" },
    { code: "FRA20", name: "Kylian Mbappe" },
  ],
  SEN: [
    { code: "SEN2",  name: "Edouard Mendy" },
    { code: "SEN3",  name: "Yehvann Diouf" },
    { code: "SEN4",  name: "Moussa Niakhaté" },
    { code: "SEN5",  name: "Abdoulaye Seck" },
    { code: "SEN6",  name: "Ismail Jakobs" },
    { code: "SEN7",  name: "El Hadji Malick Diouf" },
    { code: "SEN8",  name: "Kalidou Koulibaly" },
    { code: "SEN9",  name: "Idrissa Gana Gueye" },
    { code: "SEN10", name: "Pape Matar Sarr" },
    { code: "SEN11", name: "Pape Gueye" },
    { code: "SEN12", name: "Habib Diarra" },
    { code: "SEN14", name: "Lamine Camara" },
    { code: "SEN15", name: "Sadio Mane" },
    { code: "SEN16", name: "Ismaïla Sarr" },
    { code: "SEN17", name: "Boulaye Dia" },
    { code: "SEN18", name: "Iliman Ndiaye" },
    { code: "SEN19", name: "Nicolas Jackson" },
    { code: "SEN20", name: "Krepin Diatta" },
  ],
  IRQ: [
    { code: "IRQ2",  name: "Jalal Hassan" },
    { code: "IRQ3",  name: "Rebin Sulaka" },
    { code: "IRQ4",  name: "Hussein Ali" },
    { code: "IRQ5",  name: "Akam Hashem" },
    { code: "IRQ6",  name: "Merchas Doski" },
    { code: "IRQ7",  name: "Zaid Tahseen" },
    { code: "IRQ8",  name: "Manaf Younis" },
    { code: "IRQ9",  name: "Zidane Iqbal" },
    { code: "IRQ10", name: "Amir Al-Ammari" },
    { code: "IRQ11", name: "Ibrahim Bavesh" },
    { code: "IRQ12", name: "Ali Jasim" },
    { code: "IRQ14", name: "Youssef Amyn" },
    { code: "IRQ15", name: "Aimar Sher" },
    { code: "IRQ16", name: "Marko Farji" },
    { code: "IRQ17", name: "Osama Rashid" },
    { code: "IRQ18", name: "Ali Al-Hamadi" },
    { code: "IRQ19", name: "Aymen Hussein" },
    { code: "IRQ20", name: "Mohanad Ali" },
  ],
  NOR: [
    { code: "NOR2",  name: "Orjan Nyland" },
    { code: "NOR3",  name: "Julian Ryerson" },
    { code: "NOR4",  name: "Leo Ostigård" },
    { code: "NOR5",  name: "Kristoffer Vassbakk Ajer" },
    { code: "NOR6",  name: "Marcus Holmgren Pedersen" },
    { code: "NOR7",  name: "David Møller Wolfe" },
    { code: "NOR8",  name: "Torbjørn Heggem" },
    { code: "NOR9",  name: "Morten Thorsby" },
    { code: "NOR10", name: "Martin Ødegaard" },
    { code: "NOR11", name: "Sander Berge" },
    { code: "NOR12", name: "Andreas Schjelderup" },
    { code: "NOR14", name: "Patrick Berg" },
    { code: "NOR15", name: "Erling Haaland" },
    { code: "NOR16", name: "Alexander Sørloth" },
    { code: "NOR17", name: "Aron Dønnum" },
    { code: "NOR18", name: "Jorgen Strand Larsen" },
    { code: "NOR19", name: "Antonio Nusa" },
    { code: "NOR20", name: "Oscar Bobb" },
  ],
  ARG: [
    { code: "ARG2",  name: "Emiliano Martinez" },
    { code: "ARG3",  name: "Nahuel Molina" },
    { code: "ARG4",  name: "Cristian Romero" },
    { code: "ARG5",  name: "Nicolas Otamendi" },
    { code: "ARG6",  name: "Nicolas Tagliafico" },
    { code: "ARG7",  name: "Leonardo Balerdi" },
    { code: "ARG8",  name: "Enzo Fernandez" },
    { code: "ARG9",  name: "Alexis Mac Allister" },
    { code: "ARG10", name: "Rodrigo De Paul" },
    { code: "ARG11", name: "Exequiel Palacios" },
    { code: "ARG12", name: "Leandro Paredes" },
    { code: "ARG14", name: "Nico Paz" },
    { code: "ARG15", name: "Franco Mastantuono" },
    { code: "ARG16", name: "Nico Gonzalez" },
    { code: "ARG17", name: "Lionel Messi" },
    { code: "ARG18", name: "Lautaro Martinez" },
    { code: "ARG19", name: "Julian Alvarez" },
    { code: "ARG20", name: "Giuliano Simeone" },
  ],
  ALG: [
    { code: "ALG2",  name: "Alexis Guendouz" },
    { code: "ALG3",  name: "Ramy Bensebaini" },
    { code: "ALG4",  name: "Youcef Atal" },
    { code: "ALG5",  name: "Rayan Aït-Nouri" },
    { code: "ALG6",  name: "Mohamed Amine Tougai" },
    { code: "ALG7",  name: "Aïssa Mandi" },
    { code: "ALG8",  name: "Ismael Bennacer" },
    { code: "ALG9",  name: "Houssem Aquar" },
    { code: "ALG10", name: "Hicham Boudaoui" },
    { code: "ALG11", name: "Ramiz Zerrouki" },
    { code: "ALG12", name: "Nabil Bentalab" },
    { code: "ALG14", name: "Farés Chaibi" },
    { code: "ALG15", name: "Riyad Mahrez" },
    { code: "ALG16", name: "Said Benrahma" },
    { code: "ALG17", name: "Anis Hadj Moussa" },
    { code: "ALG18", name: "Amine Gouiri" },
    { code: "ALG19", name: "Baghdad Bounedjah" },
    { code: "ALG20", name: "Mohammed Amoura" },
  ],
  AUT: [
    { code: "AUT2",  name: "Alexander Schlager" },
    { code: "AUT3",  name: "Patrick Pentz" },
    { code: "AUT4",  name: "David Alaba" },
    { code: "AUT5",  name: "Kevin Danso" },
    { code: "AUT6",  name: "Philipp Lienhart" },
    { code: "AUT7",  name: "Stefan Posch" },
    { code: "AUT8",  name: "Phillipp Mwene" },
    { code: "AUT9",  name: "Alexander Prass" },
    { code: "AUT10", name: "Xaver Schlager" },
    { code: "AUT11", name: "Marcel Sabitzer" },
    { code: "AUT12", name: "Konrad Laimer" },
    { code: "AUT14", name: "Florian Grillitsch" },
    { code: "AUT15", name: "Nicolas Seiwald" },
    { code: "AUT16", name: "Romano Schmid" },
    { code: "AUT17", name: "Patrick Wimmer" },
    { code: "AUT18", name: "Christoph Baumgartner" },
    { code: "AUT19", name: "Michael Gregoritsch" },
    { code: "AUT20", name: "Marko Arnautović" },
  ],
  JOR: [
    { code: "JOR2",  name: "Yazeed Abulaila" },
    { code: "JOR3",  name: "Ihsan Haddad" },
    { code: "JOR4",  name: "Mohammad Abu Hashish" },
    { code: "JOR5",  name: "Yazan Al-Arab" },
    { code: "JOR6",  name: "Abdallah Nasib" },
    { code: "JOR7",  name: "Saleem Obaid" },
    { code: "JOR8",  name: "Mohammad Abualnadi" },
    { code: "JOR9",  name: "Ibrahim Saadeh" },
    { code: "JOR10", name: "Nizar Al-Rashdan" },
    { code: "JOR11", name: "Noor Al-Rawabdeh" },
    { code: "JOR12", name: "Mohannad Abu Taha" },
    { code: "JOR14", name: "Amer Jamous" },
    { code: "JOR15", name: "Musa Al-Taamari" },
    { code: "JOR16", name: "Yazan Al-Naimat" },
    { code: "JOR17", name: "Mahmoud Al-Mardi" },
    { code: "JOR18", name: "Ali Olwan" },
    { code: "JOR19", name: "Mohammad Abu Zrayq" },
    { code: "JOR20", name: "Ibrahim Sabra" },
  ],
  POR: [
    { code: "POR2",  name: "Diogo Costa" },
    { code: "POR3",  name: "Jose Sa" },
    { code: "POR4",  name: "Ruben Dias" },
    { code: "POR5",  name: "João Cancelo" },
    { code: "POR6",  name: "Diogo Dalot" },
    { code: "POR7",  name: "Nuno Mendes" },
    { code: "POR8",  name: "Gonçalo Inácio" },
    { code: "POR9",  name: "Bernardo Silva" },
    { code: "POR10", name: "Bruno Fernandes" },
    { code: "POR11", name: "João Palhinha" },
    { code: "POR12", name: "Vitinha" },
    { code: "POR14", name: "João Neves" },
    { code: "POR15", name: "Cristiano Ronaldo" },
    { code: "POR16", name: "Francisco Trincao" },
    { code: "POR17", name: "João Felix" },
    { code: "POR18", name: "Gonçalo Ramos" },
    { code: "POR19", name: "Pedro Neto" },
    { code: "POR20", name: "Rafael Leão" },
  ],
  UZB: [
    { code: "UZB2",  name: "Utkir Yusupov" },
    { code: "UZB3",  name: "Farrukh Sayfiev" },
    { code: "UZB4",  name: "Sherzod Nasrullaev" },
    { code: "UZB5",  name: "Umar Eshmurodov" },
    { code: "UZB6",  name: "Husniddin Aliqulov" },
    { code: "UZB7",  name: "Rustamjon Ashurmatov" },
    { code: "UZB8",  name: "Khojiakbar Alijonov" },
    { code: "UZB9",  name: "Abdukodir Khusanov" },
    { code: "UZB10", name: "Odiljon Hamrobekov" },
    { code: "UZB11", name: "Otabek Shukurov" },
    { code: "UZB12", name: "Jamshid Iskanderov" },
    { code: "UZB14", name: "Azizbek Turgunboev" },
    { code: "UZB15", name: "Khojimat Erkinov" },
    { code: "UZB16", name: "Eldor Shomurodov" },
    { code: "UZB17", name: "Oston Urunov" },
    { code: "UZB18", name: "Jaloliddin Masharipov" },
    { code: "UZB19", name: "Igor Sergeev" },
    { code: "UZB20", name: "Abbosbek Fayzullaev" },
  ],
  COL: [
    { code: "COL2",  name: "Camilo Vargas" },
    { code: "COL3",  name: "David Ospina" },
    { code: "COL4",  name: "Dávinson Sánchez" },
    { code: "COL5",  name: "Yerry Mina" },
    { code: "COL6",  name: "Daniel Munoz" },
    { code: "COL7",  name: "Johan Mojica" },
    { code: "COL8",  name: "Jhon Lucumí" },
    { code: "COL9",  name: "Santiago Arias" },
    { code: "COL10", name: "Jefferson Lerma" },
    { code: "COL11", name: "Kevin Castaño" },
    { code: "COL12", name: "Richard Rios" },
    { code: "COL14", name: "James Rodriguez" },
    { code: "COL15", name: "Juan Fernando Quintero" },
    { code: "COL16", name: "Jorge Carrascal" },
    { code: "COL17", name: "Jon Arias" },
    { code: "COL18", name: "Jhon Cordova" },
    { code: "COL19", name: "Luis Suarez" },
    { code: "COL20", name: "Luis Diaz" },
  ],
  COD: [
    { code: "COD2",  name: "Lionel Mpasi" },
    { code: "COD3",  name: "Aaron Wan-Bissaka" },
    { code: "COD4",  name: "Axel Tuanzebe" },
    { code: "COD5",  name: "Arthur Masuaku" },
    { code: "COD6",  name: "Chancel Mbemba" },
    { code: "COD7",  name: "Joris Kayembe" },
    { code: "COD8",  name: "Charles Pickel" },
    { code: "COD9",  name: "Ngal'ayel Mukau" },
    { code: "COD10", name: "Edo Kayembe" },
    { code: "COD11", name: "Samuel Moutoussamy" },
    { code: "COD12", name: "Noah Sadiki" },
    { code: "COD14", name: "Théo Bongonda" },
    { code: "COD15", name: "Meschak Elia" },
    { code: "COD16", name: "Yoane Wissa" },
    { code: "COD17", name: "Brian Cipenga" },
    { code: "COD18", name: "Fiston Mayele" },
    { code: "COD19", name: "Cédric Bakambu" },
    { code: "COD20", name: "Dieumerci Mbokani" },
  ],
  ENG: [
    { code: "ENG2",  name: "Jordan Pickford" },
    { code: "ENG3",  name: "John Stones" },
    { code: "ENG4",  name: "Marc Guéhi" },
    { code: "ENG5",  name: "Ezri Konsa" },
    { code: "ENG6",  name: "Trent Alexander-Arnold" },
    { code: "ENG7",  name: "Reece James" },
    { code: "ENG8",  name: "Dan Burn" },
    { code: "ENG9",  name: "Jordan Henderson" },
    { code: "ENG10", name: "Declan Rice" },
    { code: "ENG11", name: "Jude Bellingham" },
    { code: "ENG12", name: "Cole Palmer" },
    { code: "ENG14", name: "Morgan Rogers" },
    { code: "ENG15", name: "Anthony Gordon" },
    { code: "ENG16", name: "Phil Foden" },
    { code: "ENG17", name: "Bukayo Saka" },
    { code: "ENG18", name: "Harry Kane" },
    { code: "ENG19", name: "Marcus Rashford" },
    { code: "ENG20", name: "Ollie Watkins" },
  ],
  CRO: [
    { code: "CRO2",  name: "Dominik Livaković" },
    { code: "CRO3",  name: "Duje Caleta-Car" },
    { code: "CRO4",  name: "Josko Gvardiol" },
    { code: "CRO5",  name: "Josip Stanišić" },
    { code: "CRO6",  name: "Luka Vušković" },
    { code: "CRO7",  name: "Josip Sutalo" },
    { code: "CRO8",  name: "Kristijan Jakic" },
    { code: "CRO9",  name: "Luka Modrić" },
    { code: "CRO10", name: "Mateo Kovacic" },
    { code: "CRO11", name: "Martin Baturina" },
    { code: "CRO12", name: "Lovro Majer" },
    { code: "CRO14", name: "Mario Pasalic" },
    { code: "CRO15", name: "Petar Sucic" },
    { code: "CRO16", name: "Ivan Perišić" },
    { code: "CRO17", name: "Nikola Vlašić" },
    { code: "CRO18", name: "Ante Budimir" },
    { code: "CRO19", name: "Andrej Kramarić" },
    { code: "CRO20", name: "Bruno Petković" },
  ],
  GHA: [
    { code: "GHA2",  name: "Lawrence Ati Zigi" },
    { code: "GHA3",  name: "Tariq Lamptey" },
    { code: "GHA4",  name: "Mohammed Salisu" },
    { code: "GHA5",  name: "Alidu Seidu" },
    { code: "GHA6",  name: "Alexander Djiku" },
    { code: "GHA7",  name: "Gideon Mensah" },
    { code: "GHA8",  name: "Caleb Yirenkyi" },
    { code: "GHA9",  name: "Abdul Issahaku Fatawu" },
    { code: "GHA10", name: "Thomas Partey" },
    { code: "GHA11", name: "Salis Abdul Samed" },
    { code: "GHA12", name: "Kamaldeen Sulemana" },
    { code: "GHA14", name: "Mohammed Kudus" },
    { code: "GHA15", name: "Inaki Williams" },
    { code: "GHA16", name: "Jordan Ayew" },
    { code: "GHA17", name: "Andrew Ayew" },
    { code: "GHA18", name: "Joseph Paintsil" },
    { code: "GHA19", name: "Osman Bukari" },
    { code: "GHA20", name: "Antoine Semenyo" },
  ],
  PAN: [
    { code: "PAN2",  name: "Luis Mejia" },
    { code: "PAN3",  name: "Roderick Miller" },
    { code: "PAN4",  name: "Harold Cummings" },
    { code: "PAN5",  name: "Fidel Escobar" },
    { code: "PAN6",  name: "Andres Andrade" },
    { code: "PAN7",  name: "Eric Davis" },
    { code: "PAN8",  name: "Jose Cordoba" },
    { code: "PAN9",  name: "Cesar Blackman" },
    { code: "PAN10", name: "Anibal Godoy" },
    { code: "PAN11", name: "Adalberto Carrasquilla" },
    { code: "PAN12", name: "Yoel Bárcenas" },
    { code: "PAN14", name: "Édgar Bárcenas" },
    { code: "PAN15", name: "Carlos Harvey" },
    { code: "PAN16", name: "Ismael Díaz" },
    { code: "PAN17", name: "Jose Fajardo" },
    { code: "PAN18", name: "Cecilio Waterman" },
    { code: "PAN19", name: "Jose Luiz Rodriguez" },
    { code: "PAN20", name: "Alberto Quintero" },
  ],
};

/**
 * Retorna un Map de nombre normalizado → { code, team },
 * para el grupo/equipo activo (o todos si ambos son null).
 * @param {string|null} group
 * @param {string|null} teamCode
 * @returns {Map<string, { code: string, team: string }>}
 */
export function buildChecklistMap(group, teamCode) {
  const map = new Map();
  const teams = teamCode ? [teamCode] : group ? GROUPS[group] : Object.keys(CHECKLIST);
  for (const team of teams) {
    for (const entry of CHECKLIST[team] || []) {
      const name = PLAYER_ALIASES[entry.name] ?? entry.name;
      map.set(normalize(name), { code: entry.code, team });
    }
  }
  return map;
}

/**
 * Retorna el Set de country_of_citizenship a incluir según los filtros activos.
 * @param {string|null} group
 * @param {string|null} teamCode
 * @returns {Set<string>|null}
 */
export function getFilteredCountries(group, teamCode) {
  if (!group && !teamCode) return null;
  if (teamCode) return new Set([TEAM_COUNTRY[teamCode]]);
  return new Set(GROUPS[group].map((code) => TEAM_COUNTRY[code]));
}

/**
 * Devuelve los jugadores del checklist que no tienen match en el CSV.
 * @param {string} teamCode
 * @param {Set<string>} matchedCodes - Códigos de estampa ya matcheados
 * @returns {Array<{code: string, name: string, team: string}>}
 */
export function getMissingEntries(teamCode, matchedCodes) {
  return (CHECKLIST[teamCode] || []).filter((e) => !matchedCodes.has(e.code));
}
